baseURL: https://aymane11.github.io/
paginate: 5
title: enamya | blog
theme: PaperMod
enableEmoji: true

enableRobotsTXT: true
pygmentsUseClasses: true


minify:
    disableXML: true
    minifyOutput: true


params:
    env: production
    title: enamya blog
    description: "Aymane BOUMAAZA aka enamya blog"
    keywords: [Blog, enamya, Aymane BOUMAAZA]
    author: enamya
    DateFormat: "January 2, 2006"

    defaulttheme: auto
    disablethemetoggle: false
    showreadingtime: true
    showsharebuttons: true
    showtoc: true
    tocopen: false
    showbreadcrumbs: true
    showpostnavlinks: true
    showcodecopybuttons: true
    disableScrollToTop: false
    hidemeta: false
    hidesummary: true

    profileMode:
        enabled: false

    homeInfoParams:
        Title: Hi there 👋
        Content: I'm Aymane (aka Enamya), AI enthusiast, and average tech enjoyer.

    socialIcons:
        - name: "github"
          url: "https://github.com/Aymane11"
        - name: "twitter"
          url: "https://twitter.com/_Enamya"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/aymaneboumaaza"
        - name: "email"
          url: "mailto:aymaneboumaaza@gmail.com"

    editPost:
        URL: "https://github.com/Aymane11/enamya-blog/blob/main/content"
        Text: "View on GitHub"
        appendFilePath: true

    # Search
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content", "description"]

# Search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


menu:
    main:
        - id: portfolio
          name: Portfolio
          url: https://www.enamya.me/
          weight: 1
        - id: archives
          name: Archive
          url: /archives
          weight: 10
        - id: Today I Learned
          name: til
          url: /tags/til/
          weight: 100
        - identifier: tags
          name: Tags
          url: /tags
          weight: 1000
        - identifier: search
          name: Search
          url: /search
          weight: 10000

pluralizelisttitles: false
