name: deploy hugo

on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: Aymane11/aymane11.github.io
          publish_dir: ./public
          user_name: Aymane11
          user_email: aymaneboumaaza@gmail.com
          publish_branch: main
          enable_jekyll: false
          commit_message: ${{ github.event.head_commit.message }}
        #   cname: example.com